### ISSUE TITLE
libufget 1.0.2 use an outdated URL to the UF sparse collection.

### ISSUE THREAD

**Issue by grisuthedragon** [jamtrott/ex3-modules#26]
If you download a matrix with libufget 1.0.2 it downloads only the redirection notice. The bug is fixed in the 1.0.3 release, see https://doi.org/10.5281/zenodo.814642
The build script needs to be updated.

**Comment by jamtrott** [comment]
@grisuthedragon Thank you for the heads up. I have updated the script to use version 1.0.3.
